### PR TITLE
Add support for validation of single primitives

### LINKED ISSUE #21: Abreviated notation for single field validation
Would be nice be able to use an abbreviated form when you just need to validate a single field:

```
validate('string.to.be@validated.com', {email: true})
```

Is something like this currently possible?

### PR DESCRIPTION
**Pull request by franciscolourenco**
validate('example@email.com', {presence: true, email: true});

closes #21

### CODE REVIEW

**Comment by ansman** [comment]
I don't like the concept of having multi purpose functions.
It makes testing harder and there might be issues with assuming that all non objects should be validated like you propose.

I'd rather have a separate function such as `validate.short` or `validate.single` that does this.

**Comment by franciscolourenco** [comment]
The purpose would be the same, just adding flexibility to the form of input it supports.
Instead of checking non objects it could check for boolean, number and strings.
But I understand your point.

**Comment by ansman** [comment]
Do you mind moving this to https://github.com/ansman/validate.js

All further development will be done there.

**Comment by franciscolourenco** [comment]
Do you want the PR?

**Comment by ansman** [comment]
Yes please, thanks

**Pull request closed without merging**
